app = "pandorabox"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[processes]
  app = "cd frontend && npm start"

[deploy]
  strategy = "immediate"
  release_command = "npm run build"

[metrics]
  port = 3000
  path = "/metrics" 