app = "pandorabox"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    NEXT_PUBLIC_SUPABASE_URL = ""
    NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
    NEXT_PUBLIC_BACKEND_URL = ""

[env]
  PORT = "3000"
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
  NEXT_PUBLIC_BACKEND_URL = ""

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[processes]
  app = "npm start" 